### ISSUE TITLE
Meta.prefs_get_theme does not exist any more

### ISSUE THREAD

**Issue by dffischer** [mathematicalcoffee/Gnome-Shell-Window-Buttons-Extension#24]
When set to adapt to the metacity theme and run with gnome-shell 3.16, the extension fails with the notice that Meta.prefs_get_theme does not exist.

**Comment by mathematicalcoffee** [comment]
I don't have time to fix this now (do I ever? :[) but note to self for when I can find some time: https://mail.gnome.org/archives/gnome-shell-list/2015-April/msg00022.html

Try Gtk.Settings.get_default().gtk_theme_name  instead of Meta.prefs_get_theme  [unsure if gtk_theme_name() or gtk_theme_name, try it out in the looking glass]

**Comment by dffischer** [comment]
It needs to be looked into, indeed. I tried a simple replacement as suggested. The result was a complete crash of gnome shell as soon as the extension was activated.

The mail you referenced was written by the developer of [pixel-saver](https://github.com/deadalnix/pixel-saver) which essentially combines the functionality of your extensions maximus and window-buttons. They seem quite active over there sorting out their bugs.

**Comment by mathematicalcoffee** [comment]
that's great, perhaps I should write a note on maximus and redirect people to pixel-saver or contact deadalnix to see if he wants to take over? I haven't updated maximus etc since about 3.8. I'd like to get back into it, but don't have much time for it.

**Comment by dffischer** [comment]
Pulling in [danielkza's fork](https://github.com/danielkza/Gnome-Shell-Window-Buttons-Extension) magically fixed this. Unfortunately, #23 still keeps it from working on 3.16.
